### ISSUE TITLE
Create an awesome logo for the library

### ISSUE THREAD

**Issue by dmitry-potepalov** [aiven/rohmu#9]

**Comment by evche-aiven** [comment]
![Rohmu-logo](https://user-images.githubusercontent.com/64008564/165510615-fa779e4f-7bd9-4167-aed7-256227b4799b.svg)

**Comment by evche-aiven** [comment]
![rohmu-logo](https://user-images.githubusercontent.com/64008564/165512224-38b616bc-0580-4587-a728-1910082ea727.svg)

**Comment by evche-aiven** [comment]
Done, we can adjust the size to fit, incase its needed

**Comment by evche-aiven** [comment]
![Rohmu-logo-header](https://user-images.githubusercontent.com/64008564/165527147-4b80278d-0764-4c98-851b-70e2f4c08647.png)
